version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tie
      MONGO_INITDB_ROOT_PASSWORD: sec1.01
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tie
      ME_CONFIG_MONGODB_ADMINPASSWORD: sec1.01
      ME_CONFIG_MONGODB_URL: mongodb://tie:sec1.01@mongo:27017/

volumes:
  mongodata:
    driver: local