version: '3.8'

volumes:
  postgres-data:


services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sec1.01
      POSTGRES_USER: tie
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tie.ch
      PGADMIN_DEFAULT_PASSWORD: sec1.01