spring:
  datasource:
    url: jdbc:mariadb://chucknorris.tie.local:40000/lehrverwaltung
    username: tie
    password: sec1.01
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    session:
      timeout: 420m
logging:
  level:
    tie:
      lehrlinge:
        lehrverwaltung:
          server:
            service:
              DEBUG
            util:
              DEBUG
docker-java:
  image:
    name: ghcr.io/graalvm/graalvm-ce:latest
  host:
    url: tcp://chucknorris.tie.local:2375
  container:
    name: bladerunner
